name: 'Build and test'

on: [ push ]

env:
  BUILD_TYPE: Debug

jobs:
  build_and_test:
    runs-on: ubuntu-20.04

    name: 'Build and test'

    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: 'apt-get update'
        shell: bash
        run: 'sudo apt-get update'

      - name: 'Install dependency: clang-format-11'
        shell: bash
        run: 'sudo apt-get install clang-format-11'

      - name: 'Check formatting'
        shell: bash
        working-directory: '${{github.workspace}}'
        run: |
          shopt -s globstar
          clang-format-11 --dry-run -Werror src/**/*.cpp src/**/*.h tests/**/*.cpp

      - name: 'Install dependency: boost'
        shell: bash
        run: 'sudo apt-get install libboost-all-dev'

      - name: 'Create build environment'
        run: 'cmake -E make_directory ${{github.workspace}}/build'

      - name: 'Configure CMake'
        shell: bash
        working-directory: '${{github.workspace}}/build'
        run: 'cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE'

      - name: 'Build server'
        working-directory: '${{github.workspace}}/build'
        shell: bash
        run: 'cmake --build . --config $BUILD_TYPE --target crossing_consoles_main_server'

      - name: 'Build client'
        working-directory: '${{github.workspace}}/build'
        shell: bash
        run: 'cmake --build . --config $BUILD_TYPE --target crossing_consoles_main_client'

      - name: 'Build tests'
        working-directory: '${{github.workspace}}/build'
        shell: bash
        run: 'cmake --build . --config $BUILD_TYPE --target crossing_consoles_test'

      - name: 'Run tests'
        working-directory: '${{github.workspace}}/build'
        shell: bash
        run: './tests/crossing_consoles_test'
